AllCops:
  Exclude:
    - 'lib/mtree/parser.tab.rb'
    - 'vendor/bundle/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
