AllCops:
  NewCops: "enable"
  TargetRubyVersion: "2.7"
  Exclude:
    - 'lib/mtree/parser.tab.rb'

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
